// Code generated by "enumer -type=Padding types.go"; DO NOT EDIT

package padding

const _Padding_name = "SAMEVALID"

var _Padding_index = [...]uint8{0, 4, 9}

func (i Padding) String() string { _ = "STUB: not implemented"; return "" }

var _PaddingNameToValue_map = map[string]Padding{
	_Padding_name[0:4]: 0,
	_Padding_name[4:9]: 1,
}

func PaddingString(s string) (Padding, error) { _ = "STUB: not implemented"; return *new(Padding), nil }
